### PR TITLE
adapter configuration for 0.6.x 

### PR DESCRIPTION
**Pull request by kucaahbe**
Added possibility to pass any additional adapter configuration for 0.6.x version. Please, let me know if any other things I need to do in order to this PR could be submitted.

### CODE REVIEW

**Comment by joneslee85** [comment]
@kucaahbe it'd be nice if you could provide usecases for this change. Besides, this version is too old.

**Comment by kucaahbe** [comment]
@joneslee85 for instance to pass any option in order to configure Sequel, e.g. `sslmode`

**Comment by AlfonsoUceda** [comment]
@kucaahbe why modify this version, can't you update to the last one? maybe the new model version can use that, @jodosha can you confirm us this?

**Comment by kucaahbe** [comment]
@AlfonsoUceda for the moment when PR was created there wasn't later version (as far as I remember), only master branch. So, assuming this change could be useful, don't break anything and could be merged to future versions I've created PR for 0.6.x. Let me know how can I improve PR and against which branch it should be submitted, thanks!

**Comment by jodosha** [comment]
@kucaahbe Hi, what's your use case? IIRC you can express extra options for Sequel via query string: eg. `postgres://localhost/bookshelf_development?extra_option=here`. Can you please try if this works for you? Thanks.

**Comment by AlfonsoUceda** [comment]
Sorry, but I don't agree create new tags for an old version when we are under version 1.0, I think the only purpose for creating a new tag for an old version is for security reasons.

@kucaahbe could you check what @jodosha said?

**Comment by kucaahbe** [comment]
@jodosha @AlfonsoUceda proposed solution tend to work, but worth to mention that it probably would be nice to have database configuration separation, where some part of configuration is local and some is global, (e.g. encoding option). However if it's too hard (so much use-cases to learn and tags to create, just kidding) ), than don't see a reason to keep this pr open, thanks!

**Comment by AlfonsoUceda** [comment]
@kucaahbe thanks, but this can be proposed in master instead this one, we can discuss about that ;)

**Pull request closed without merging**
