### PR TITLE
Support for association aliasing

### PR DESCRIPTION
**Pull request by mereghost**
This small patch adds alias support for hanami associations

```
class UserRepository < Hanami::Repository
  associations do
    has_many :posts
  end
end

class PostRepository < Hanami::Repository
  associations do
    belongs_to :user, as: :author
  end

  def latest_10_posts
    aggregates(:author).reverse(:created_at).limit(10).map_to(Post).to_a
  end
end 

#=> [Post(title: 'Awesomeness in a Jar`, author: User(name: 'InternetPerson'))] 
```

### CODE REVIEW

**Comment by mereghost** [comment]
@jodosha Any ideas on how to test this thing?

**Comment by jodosha** [comment]
@mereghost Wow, thanks for the quick implementation!

I think we can test it with the scenario in the description of this PR. 😉

**Comment by mereghost** [comment]
Ok. I'll put some tests up.

**Comment by mereghost** [comment]
And I fucked up by clicking the wrong button XD

**Comment by mereghost** [comment]
I updated the tests to be somewhat comprehensible for the feature. The support for `#assoc` calls on many-to-many implementation still needs to be done.

**Comment by AlfonsoUceda** [comment]
just asking, if we support an alias `belongs_to :user, as: :author` then we can't call `.user`, isn't it?

**Comment by mereghost** [comment]
@AlfonsoUceda well, the repository talks to relations directly, so the alias won't work at all. The singular for used on a `belongs_to` call is just a kind of alias for the relation (which uses the pluralized form).

The alias will only be used to construct aggregates, like in the example you gave the attribute of the returned object will be called `author` and you'll need to call `aggregate(:author)`.

**Comment by mereghost** [comment]
Here's my test case: 

```ruby
class Story < Hanami::Entity
end

class User < Hanami::Entity
end

class Comment < Hanami::Entity
end

class UserRepository < Hanami::Repository
  associations do
    has_many :comments
    has_many :stories
  end
end

class CommentRepository < Hanami::Repository
  associations do
    belongs_to :user
    belongs_to :story
  end
end

class StoryRepository < Hanami::Repository
  associations do
    belongs_to :user, as: :author
    has_many :comments
    has_many :users, through: :comments, as: :commenters
  end

  def commenters_for(story)
    assoc(:commenters).to_a
  end
  
  def feed
    aggregate(:author, comments: :commenter).map_to(Story)
  end
end
```
For now every association there works for aggregation and `#assoc` calls. As soon as you throw an alias on the `belongs_to` of the association repo (`CommentRepository` in this case) everything explodes.

This seems to be a limitation of `ROM`, tho (as I got the same problems using rom-repo et al). I'll explore some more and then talk to them about it. For now I'm cleaning up this PR and prepping it for release.

**Comment by jodosha** [comment]
I also tried with:

```ruby
class StoryRepository < Hanami::Repository
  associations do
    belongs_to :user
    has_many :comments
    has_many :users, through: :comments, as: :authors
  end

  def feed
    aggregate(:user, comments: :authors).reverse(:created_at).map_to(Story)
  end
end
```

**Comment by mereghost** [comment]
@jodosha Let me see...

In your first example you are asking for an aggregate of `user` and `comments` with its `authors`. Under the hood, `rom` tries to:

1. if `users` relation is available, then add it to the aggregate otherwise explode.
1. same goes with `comments`
1. then it looks to `comments` and asks: "do you have an author relation?" and if not explode.

One way to solve your aggregation is by aliasing `users` on `CommentRepository` (`belongs_to :user, as: :author)`.

The `has_many :through` in this case being unnecessary, unless you want to recover all the commentators without the comments themselves.

That being said, it seems that `rom` gets lost once you alias a `belongs_to` that gets used on a `has_many :through` association.

**Comment by jodosha** [comment]
@mereghost 



> One way to solve your aggregation is by aliasing users on CommentRepository (belongs_to :user, as: :author).

```
/Users/luca/.gem/ruby/2.4.2/gems/hanami-model-1.1.0.beta3/lib/hanami/model/configuration.rb:144:in `rescue in load!': key not found: :author (Hanami::Model::Error)
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-model-1.1.0.beta3/lib/hanami/model/configuration.rb:134:in `load!'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-model-1.1.0.beta3/lib/hanami/model.rb:79:in `load!'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components/components.rb:89:in `block (2 levels) in <module:Components>'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components/component.rb:44:in `call'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:108:in `block (2 levels) in resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:106:in `block in resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:105:in `each'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:105:in `resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components/component.rb:138:in `resolve_requirements'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components/component.rb:36:in `call'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:108:in `block (2 levels) in resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
	from /Users/luca/.gem/ruby/2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:106:in `block in resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:105:in `each'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami/components.rb:105:in `resolve'
	from /Users/luca/.gem/ruby/2.4.2/gems/hanami-1.1.0.beta3/lib/hanami.rb:92:in `boot'
	from /Users/luca/Code/teamnow/spec/spec_helper.rb:5:in `<top (required)>'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `require'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `block in requires='
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `each'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `requires='
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `each'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
/Users/luca/.rubies/ruby-2.4.2/bin/ruby -I/Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/lib:/Users/luca/.gem/ruby/2.4.2/gems/rspec-support-3.6.0/lib /Users/luca/.gem/ruby/2.4.2/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by jodosha** [comment]
Travis CI 😡

**Pull request merged**
