### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by TheFarmingBunny**
Add jruby-pg for better support on some jruby platforms

### CODE REVIEW

**Comment by TheFarmingBunny** [comment]
No Travis failures are related to this.

**Comment by jodosha** [comment]
@TheFarmingBunny Hi and thanks for this PR. The target branch is `new-engine` which is behind the progress that ROM did in the last month. Once, I'll update the code, I'll take care to merge this PR.

How `jruby-pg` is better? Thanks!

**Comment by TheFarmingBunny** [comment]
`jruby-pg` has slightly more features and can be simply required using `require 'pg'`. It also doesn't require jdbc: to be appended to database urls and, in my experience, I have run into problems while using jdbc-postgres.

10.08.2016, 11:36, "Luca Guidi" <notifications@github.com>:

**Comment by jodosha** [comment]
@TheFarmingBunny Thanks for the clarification. Do you if there are alternatives for MySQL and SQLite3 too?

**Comment by TheFarmingBunny** [comment]
I don't know of any alternatives for them.

**Comment by TheFarmingBunny** [comment]
Do we require pg 0.18? If so that might be a block according to this issue:
https://github.com/headius/jruby-pg/issues/25

**Comment by jodosha** [comment]
@TheFarmingBunny There is no restriction to the `pg` version.

**Comment by TheFarmingBunny** [comment]
That's great

**Comment by AlfonsoUceda** [comment]
@TheFarmingBunny could you close this PR and open a new one comparing to master?

**Comment by TheFarmingBunny** [comment]
Sure!

**Comment by Hiroyuki-Nagata** [comment]
I want to deploy hanami with JRuby & Heroku & Postgresql.
This feature is interesting.

**Pull request closed without merging**
