### PR TITLE
Migrate to rspec 

### PR DESCRIPTION
**Pull request by bbonislawski**
Work for #392 

I'm not sure about my way of including examples for database-specific migrations. RSpec doesn't allow you to load specs with `load` AFAIK. 

Please correct me if I'm wrong and there is better way to do that

### CODE REVIEW

**Comment by jodosha** [comment]
@bbonislawski Hi and thanks for this PR. Which specs are still missing?

**Comment by bbonislawski** [comment]
@jodosha I didn't mean there are missing specs. I'm not sure if https://github.com/hanami/model/pull/396/files#diff-9822821bd605b402d1e2e6e2a28989db 
this is good solution for the problem and I'd like to get some feedback about it

**Comment by jodosha** [comment]
@bbonislawski I've finally merged this. Thank you again! 👍

**Comment by solnic** [comment]
YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES

**Comment by bbonislawski** [comment]
It was pleasure!

**Pull request merged**
